language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
branches:
  only:
  - master
install:
  # Build/test dependencies
  - pip install -r dev-requirements.txt
  # install fab to test fab
  - pip install -e .
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
before_script:
  # Allow us to SSH passwordless to localhost
  - ssh-keygen -f ~/.ssh/id_rsa -N ""
  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
  # Creation of an SSH agent for testing forwarding
  - eval $(ssh-agent)
  - ssh-add
script:
  - flake8
  # Normal tests
  - fab test
  # Integration tests
  - fab -H localhost test:"--tests\=integration"
  # Build docs; www first without warnings so its intersphinx objects file
  # generates. Then docs (with warnings->errors), then www again (also w/
  # warnings on.) FUN TIMES WITH CIRCULAR DEPENDENCIES.
  # - invoke www
  # - invoke docs -o -W
  # - invoke www -c -o -W
notifications:
  email: false
